POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "joao",
    "email": "joao@hotmail.com",
    "password": "joao55605123"
}

###

GET http://localhost:3003/users

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "joao",
    "price": "5000",
    "image_url": "https://s2.glbimg.com/_7ptw6NKzcKabtkw5mTrmW-VgeQ=/13x0:1363x767/1008x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/I/H/bM8pGFRMOnPKvyQ6T9tw/playstation-5.jpg"
}

###

GET http://localhost:3003/products
